<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
    <PackageReference Include="administradorcore.basehost" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog.Enrichers.CorrelationId" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Sinks.ElasticSearch" />
    <ProjectReference Include="..\Tyc.Implementacion\Tyc.Implementacion.csproj" />
    <ProjectReference Include="..\Tyc.Interface\Tyc.Interface.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Resources\logoAnato.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\logo_default.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\consentimiento-creado.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\consentimiento-firmado.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\EmailFinProceso.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\EmailNotificacion.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\EmailRecuperarClaveEN.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\EmailRecuperarClaveES.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\Logo.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\mail-agradecimiento.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\mail-invitacion.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Templates\testCorreoProceso.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Middleware\" />
	</ItemGroup>
  
</Project>
