//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyc.Interface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sigo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sigo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tyc.Interface.Resources.Sigo", typeof(Sigo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo debe existir una archivo con extencion .dbf.
        /// </summary>
        internal static string CapaArchivoExiste {
            get {
                return ResourceManager.GetString("CapaArchivoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capa creada con exito.
        /// </summary>
        internal static string CapaCreacion {
            get {
                return ResourceManager.GetString("CapaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear la capa.
        /// </summary>
        internal static string CapaCreacionError {
            get {
                return ResourceManager.GetString("CapaCreacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capa actualizada con exito.
        /// </summary>
        internal static string CapaEditar {
            get {
                return ResourceManager.GetString("CapaEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar la capa.
        /// </summary>
        internal static string CapaEditarError {
            get {
                return ResourceManager.GetString("CapaEditarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capa generada actualizada con exito.
        /// </summary>
        internal static string CapaGeneradaActualizacion {
            get {
                return ResourceManager.GetString("CapaGeneradaActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar la Consulta.
        /// </summary>
        internal static string CapaGeneradaActualizacionError {
            get {
                return ResourceManager.GetString("CapaGeneradaActualizacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capa generada creada con exito.
        /// </summary>
        internal static string CapaGeneradaInsertar {
            get {
                return ResourceManager.GetString("CapaGeneradaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intenrar crear la capa generada.
        /// </summary>
        internal static string CapaGeneradaInsertarError {
            get {
                return ResourceManager.GetString("CapaGeneradaInsertarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consulta no retorna puntos.
        /// </summary>
        internal static string CapaGeneradaValidacionConsultaPuntosSinDatos {
            get {
                return ResourceManager.GetString("CapaGeneradaValidacionConsultaPuntosSinDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La referencia debe ser unico en el sistema.
        /// </summary>
        internal static string CapaReferenciaExiste {
            get {
                return ResourceManager.GetString("CapaReferenciaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo comprimido no contiene un archivo .dbf.
        /// </summary>
        internal static string CapaValidacionArchivoZip {
            get {
                return ResourceManager.GetString("CapaValidacionArchivoZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La carga masiva se hizo con éxito!!.
        /// </summary>
        internal static string CargaExitosa {
            get {
                return ResourceManager.GetString("CargaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La carga no tuvo éxito!!.
        /// </summary>
        internal static string CargaSinExito {
            get {
                return ResourceManager.GetString("CargaSinExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta espacial actualizada con exito.
        /// </summary>
        internal static string ConsultaEspacialActualizar {
            get {
                return ResourceManager.GetString("ConsultaEspacialActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar la consulta espacial.
        /// </summary>
        internal static string ConsultaEspacialActualizarError {
            get {
                return ResourceManager.GetString("ConsultaEspacialActualizarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta espacial creada con exito.
        /// </summary>
        internal static string ConsultaEspacialInsertar {
            get {
                return ResourceManager.GetString("ConsultaEspacialInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar crear la consulta espacial.
        /// </summary>
        internal static string ConsultaEspacialInsertarError {
            get {
                return ResourceManager.GetString("ConsultaEspacialInsertarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string DespachoInsertarError {
            get {
                return ResourceManager.GetString("DespachoInsertarError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string NovedadOperativaInsertarError
        {
            get
            {
                return ResourceManager.GetString("NovedadOperativaInsertarError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No puede realizar esta acción por que existe novedad de varada o salida de frecuencia en estado abierto.
        /// </summary>
        internal static string ErrorCerrarViajeNovedadesAbiertas {
            get {
                return ResourceManager.GetString("ErrorCerrarViajeNovedadesAbiertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violacion de tiempo al cerrar Viaje.
        /// </summary>
        internal static string ErrorCerrarViajeViolacionTiempo {
            get {
                return ResourceManager.GetString("ErrorCerrarViajeViolacionTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se insertaron datos!!.
        /// </summary>
        internal static string SinDatos {
            get {
                return ResourceManager.GetString("SinDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta persona ya ha sido asignado en otro Despacho! Verifique los datos..
        /// </summary>
        internal static string UsuarioAsignadoOtroDespacho {
            get {
                return ResourceManager.GetString("UsuarioAsignadoOtroDespacho", resourceCulture);
            }
        }
    }
}
