<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="wwwroot\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="wwwroot\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="administradorcore.implementacion" />
    <PackageReference Include="administradorcore.cifrar" />
    <PackageReference Include="AWSSDK.SimpleEmailV2" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="QuestPDF" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyc.Interface\Tyc.Interface.csproj" />
    <ProjectReference Include="..\Tyc.Modelo\Tyc.Modelo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Parametrizacion\Mappings\" />
    <Folder Include="Parametrizacion\Repositories\" />
  </ItemGroup>

</Project>
