using Mapster;
using Tyc.Interface.Request;
using Tyc.Interface.Response;
using Tyc.Modelo.Contexto;
using System;

namespace Tyc.Implementacion.Empresas.Mappings;

public class EmpresaMappingConfig : IRegister
{
    public void Register(TypeAdapterConfig config)
    {
        // Entity a Response
        config.NewConfig<Empresa, EmpresaResponse>()
            .Map(dest => dest.Id, src => src.EmpresaId)
            .Map(dest => dest.Guid, src => src.Guid)
            .Map(dest => dest.Nombre, src => src.Nombre)
            .Map(dest => dest.CiudadEmpresa, src => src.CiudadEmpresa)
            .Map(dest => dest.Direccion, src => src.Direccion)
            .Map(dest => dest.Telefono, src => src.Telefono)
            .Map(dest => dest.Website, src => src.Website)
            .Map(dest => dest.MailContactos, src => src.MailContactos)
            .Map(dest => dest.LogoEmpresa, src => src.LogoBase64) 
			.Map(dest => dest.LogoIso9000, src => src.LogoIso9000)
            .Map(dest => dest.LogoIso27001, src => src.LogoIso27001)
            .Map(dest => dest.NombreContacto, src => src.NombreContacto)
            .Map(dest => dest.MailDelContacto, src => src.MailDelContacto)
            .Map(dest => dest.TelContacto, src => src.TelContacto)
            .Map(dest => dest.Subdominio, src => src.Subdominio)
            .Map(dest => dest.ManejaTerminosYCondiciones, src => src.ManejaTerminosYCondiciones)
            .Map(dest => dest.ManejaTycCompartirInfo, src => src.ManejaTycCompartirInfo)
            .Map(dest => dest.ManejaTycRecibirOfertas, src => src.ManejaTycRecibirOfertas)
            .Map(dest => dest.ContactabilidadSms, src => src.ContactabilidadSms)
            .Map(dest => dest.ContactabilidadEmail, src => src.ContactabilidadEmail)
            .Map(dest => dest.ContactabilidadWhatsapp, src => src.ContactabilidadWhatsapp)
            .Map(dest => dest.ContactabilidadMovil, src => src.ContactabilidadMovil)
            .Map(dest => dest.SolicitaNombre, src => src.SolicitaNombre)
            .Map(dest => dest.SolicitaApellido, src => src.SolicitaApellido)
            .Map(dest => dest.SolicitaEmail, src => src.SolicitaEmail)
            .Map(dest => dest.SolicitaTelefono, src => src.SolicitaTelefono)
            .Map(dest => dest.SolicitaIdentificacion, src => src.SolicitaIdentificacion)
            .Map(dest => dest.Estado, src => src.Estado)
            .Map(dest => dest.ManejaCorporativo, src => src.ManejaCorporativo)
            .Map(dest => dest.ManejaConsolidacion, src => src.ManejaConsolidacion)
            .Map(dest => dest.ManejaReceptivo, src => src.ManejaReceptivo)
            .Map(dest => dest.ManejaMayoreo, src => src.ManejaMayoreo)
            .Map(dest => dest.ManejaEventos, src => src.ManejaEventos);

        // CreateRequest a Entity
        config.NewConfig<CreateEmpresa, Empresa>()
            .Map(dest => dest.Guid, src => Guid.NewGuid())
            .Map(dest => dest.Nombre, src => src.Nombre)
            .Map(dest => dest.CiudadEmpresa, src => src.CiudadEmpresa)
            .Map(dest => dest.Direccion, src => src.Direccion)
            .Map(dest => dest.Telefono, src => src.Telefono)
            .Map(dest => dest.Website, src => src.Website)
            .Map(dest => dest.MailContactos, src => src.MailContactos)
            .Map(dest => dest.LogoBase64, src => src.LogoEmpresa)
			.Map(dest => dest.LogoIso9000, src => src.TieneIso9000)
            .Map(dest => dest.LogoIso27001, src => src.TieneIso27001)
            .Map(dest => dest.NombreContacto, src => src.NombreContacto)
            .Map(dest => dest.MailDelContacto, src => src.MailDelContacto)
            .Map(dest => dest.TelContacto, src => src.TelContacto)
            .Map(dest => dest.Subdominio, src => src.Subdominio)
            .Map(dest => dest.ManejaTerminosYCondiciones, src => src.ManejaTerminosYCondiciones)
            .Map(dest => dest.ManejaTycCompartirInfo, src => src.ManejaTycCompartirInfo)
            .Map(dest => dest.ManejaTycRecibirOfertas, src => src.ManejaTycRecibirOfertas)
            .Map(dest => dest.ContactabilidadSms, src => src.ContactabilidadSms)
            .Map(dest => dest.ContactabilidadEmail, src => src.ContactabilidadEmail)
            .Map(dest => dest.ContactabilidadWhatsapp, src => src.ContactabilidadWhatsapp)
            .Map(dest => dest.ContactabilidadMovil, src => src.ContactabilidadMovil)
            .Map(dest => dest.SolicitaNombre, src => src.SolicitaNombre)
            .Map(dest => dest.SolicitaApellido, src => src.SolicitaApellido)
            .Map(dest => dest.SolicitaEmail, src => src.SolicitaEmail)
            .Map(dest => dest.SolicitaTelefono, src => src.SolicitaTelefono)
            .Map(dest => dest.SolicitaIdentificacion, src => src.SolicitaIdentificacion)
            .Map(dest => dest.Estado, src => EstadoBloqueoEmpresa.NoBloqueada)
            .Map(dest => dest.ManejaCorporativo, src => src.ManejaCorporativo)
            .Map(dest => dest.ManejaConsolidacion, src => src.ManejaConsolidacion)
            .Map(dest => dest.ManejaReceptivo, src => src.ManejaReceptivo)
            .Map(dest => dest.ManejaMayoreo, src => src.ManejaMayoreo)
            .Map(dest => dest.ManejaEventos, src => src.ManejaEventos)
            .Ignore(dest => dest.EmpresaId);

        // UpdateRequest a Entity
        config.NewConfig<UpdateEmpresa, Empresa>()
            .Map(dest => dest.EmpresaId, src => src.Id)
            .Map(dest => dest.Nombre, src => src.Nombre)
            .Map(dest => dest.CiudadEmpresa, src => src.CiudadEmpresa)
            .Map(dest => dest.Direccion, src => src.Direccion)
            .Map(dest => dest.Telefono, src => src.Telefono)
            .Map(dest => dest.Website, src => src.Website)
            .Map(dest => dest.MailContactos, src => src.MailContactos)
            .Map(dest => dest.LogoBase64, src => src.LogoEmpresa)
			.Map(dest => dest.LogoIso9000, src => src.LogoIso9000)
            .Map(dest => dest.LogoIso27001, src => src.LogoIso27001)
            .Map(dest => dest.NombreContacto, src => src.NombreContacto)
            .Map(dest => dest.MailDelContacto, src => src.MailDelContacto)
            .Map(dest => dest.TelContacto, src => src.TelContacto)
            .Map(dest => dest.Subdominio, src => src.Subdominio)
            .Map(dest => dest.ManejaTerminosYCondiciones, src => src.ManejaTerminosYCondiciones)
            .Map(dest => dest.ManejaTycCompartirInfo, src => src.ManejaTycCompartirInfo)
            .Map(dest => dest.ManejaTycRecibirOfertas, src => src.ManejaTycRecibirOfertas)
            .Map(dest => dest.ContactabilidadSms, src => src.ContactabilidadSms)
            .Map(dest => dest.ContactabilidadEmail, src => src.ContactabilidadEmail)
            .Map(dest => dest.ContactabilidadWhatsapp, src => src.ContactabilidadWhatsapp)
            .Map(dest => dest.ContactabilidadMovil, src => src.ContactabilidadMovil)
            .Map(dest => dest.SolicitaNombre, src => src.SolicitaNombre)
            .Map(dest => dest.SolicitaApellido, src => src.SolicitaApellido)
            .Map(dest => dest.SolicitaEmail, src => src.SolicitaEmail)
            .Map(dest => dest.SolicitaTelefono, src => src.SolicitaTelefono)
            .Map(dest => dest.SolicitaIdentificacion, src => src.SolicitaIdentificacion)
            .Map(dest => dest.ManejaCorporativo, src => src.ManejaCorporativo)
            .Map(dest => dest.ManejaConsolidacion, src => src.ManejaConsolidacion)
            .Map(dest => dest.ManejaReceptivo, src => src.ManejaReceptivo)
            .Map(dest => dest.ManejaMayoreo, src => src.ManejaMayoreo)
            .Map(dest => dest.ManejaEventos, src => src.ManejaEventos)
            .Ignore(dest => dest.Guid)
            .Ignore(dest => dest.Estado);
    }
}